---
name: "Build - ARM"

on:
  push:
    branches:
    - master
    - 'cog-*'
  pull_request:
    branches:
    - master
    - 'cog-*'

jobs:
  build:
    strategy:
      matrix:
        buildtype: [release, debug]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/toolchain
          key: arm-${{ runner.os }}-${{ hashFiles('.github/toolchain.sh') }}
          restore-keys: tc-${{ runner.os }}-
      - name: Install Toolchain
        run: |-
          .github/toolchain.sh ~/toolchain
      - name: Configure
        env:
          BUILD_TYPE: ${{ matrix.buildtype }}
        run: |-
          . ~/toolchain/environment-setup-*-poky-linux-gnueabi
          meson build --buildtype "${BUILD_TYPE}" \
            -Dplatforms=drm,headless,wayland \
            -Dprograms=true \
            -Ddocumentation=false \
            -Dmanpages=false \
            -Dlibportal=disabled \
            -Dwpe_api=1.1
      - name: Build
        env:
          TERM: dumb
        run:
          . ~/toolchain/environment-setup-*-poky-linux-gnueabi
          ninja -C build
